export const POKEMON_LOADING = 'POKEMON/LOADING'
export const POKEMON_SUCCESS = 'POKEMON/SUCCES'
export const POKEMON_ERROR = 'POKEMON/ERROR'

export const DETAIL_POKEMON_LOADING = 'DETAIL/POKEMON/LOADING'
export const DETAIL_POKEMON_SUCCESS = 'DETAIL/POKEMON/SUCCES'
export const DETAIL_POKEMON_ERROR = 'DETAIL/POKEMON/ERROR'